const IMG = {
  bruno: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=500&q=88',
  luna: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=500&q=88',
  ananya: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=88',
  meera: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=500&q=88',
  arjun: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=500&q=88',
  priya: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=88',
  care: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=86',
  article: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=86'
};

const pages = [
  ['Entry', 'splash', 'Splash'], ['Entry', 'welcome', 'Welcome'], ['Entry', 'sign-in', 'Email sign in'], ['Entry', 'otp', 'Phone OTP'], ['Entry', 'create-account', 'Create account'], ['Entry', 'reset-password', 'Reset password'],
  ['Home', 'home', 'Home'], ['Home', 'notifications', 'Notifications'],
  ['Find care', 'find-care', 'Find care'], ['Find care', 'search-filters', 'Search filters'], ['Find care', 'map', 'Nearby vets map'], ['Find care', 'vet', 'Vet profile'], ['Find care', 'reviews', 'Reviews'],
  ['Booking', 'booking-pet', 'Booking: pet & type'], ['Booking', 'booking-time', 'Booking: date & time'], ['Booking', 'booking-reason', 'Booking: visit reason'], ['Booking', 'booking-review', 'Booking: review'], ['Booking', 'payment', 'Payment checkout'], ['Booking', 'confirmation', 'Confirmation'],
  ['Appointments', 'appointments', 'Appointments'], ['Appointments', 'appointment', 'Appointment detail'], ['Appointments', 'reschedule', 'Reschedule'], ['Appointments', 'cancel', 'Cancel appointment'], ['Appointments', 'review', 'Submit review'],
  ['Consultation', 'modality', 'Choose modality'], ['Consultation', 'device-check', 'Device check'], ['Consultation', 'consultation', 'Video consultation'], ['Consultation', 'consultation-chat', 'Consultation chat'], ['Consultation', 'visit-summary', 'Visit summary'], ['Consultation', 'assistant', 'AI Pet Assistant'],
  ['Pets', 'pets', 'Pets'], ['Pets', 'pet-edit', 'Add / edit pet'], ['Pets', 'pet-health', 'Pet health'], ['Pets', 'timeline', 'Medical timeline'], ['Pets', 'medical-record', 'Medical record'], ['Pets', 'medications', 'Medications'], ['Pets', 'medication-edit', 'Add medication'], ['Pets', 'reminders', 'Reminders'], ['Pets', 'reminder-edit', 'Add reminder'], ['Pets', 'prescriptions', 'Prescriptions'], ['Pets', 'documents', 'Documents'],
  ['Money', 'wallet', 'Payments & wallet'], ['Money', 'payment-history', 'Payment history'], ['Money', 'payment-detail', 'Payment detail'], ['Money', 'plans', 'Subscription plans'],
  ['Content', 'articles', 'Pet care articles'], ['Content', 'article', 'Article detail'],
  ['Profile', 'profile', 'Profile'], ['Profile', 'profile-edit', 'Edit profile'], ['Profile', 'security', 'Password & security'], ['Profile', 'notification-settings', 'Notification preferences'], ['Profile', 'help', 'Help & support'], ['Profile', 'legal', 'Legal & about'], ['Profile', 'delete-account', 'Delete account'], ['Profile', 'server-settings', 'Server settings'],
  ['Emergency', 'emergency', 'Emergency care'], ['Emergency', 'sos-tracker', 'SOS live tracker']
];

const state = {
  careGiven: false,
  booking: { pet: 'Bruno', type: 'Clinic visit', date: 'Today, 24 May', time: '5:15 PM', reason: 'Routine check-up' },
  appointmentTab: 'Upcoming',
  recordTab: 'Timeline',
  searchFilter: 'All',
  selectedPlan: 'Plus',
  notificationsRead: false,
  call: { mic: true, camera: true, chat: false },
  sosStage: 1,
  messages: [
    { from: 'bot', text: 'Hi Priya! I’m your AI Pet Assistant. How can I help you and Bruno today?' },
    { from: 'me', text: 'Bruno has been scratching near his ears since yesterday.' },
    { from: 'bot', text: 'It could be allergies, ear mites, or irritation. Check for redness, odor, swelling, or discharge. Would you like home-care tips or help finding a vet?' }
  ]
};

const icons = {
  back: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="m15 18-6-6 6-6"/></svg>',
  bell: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>',
  home: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="m3 11 9-8 9 8v10h-6v-6H9v6H3Z"/></svg>',
  search: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>',
  calendar: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4M3 10h18"/></svg>',
  pet: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><ellipse cx="12" cy="16" rx="5" ry="4"/><circle cx="6.5" cy="9" r="2"/><circle cx="10" cy="6" r="2"/><circle cx="14" cy="6" r="2"/><circle cx="17.5" cy="9" r="2"/></svg>',
  user: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',
  video: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="3" y="5" width="14" height="14" rx="3"/><path d="m17 9 4-2v10l-4-2z"/></svg>',
  plus: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>',
  check: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="m5 12 4 4L19 6"/></svg>',
  pill: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="m9.5 4.5 10 10a4 4 0 0 1-5.7 5.6l-10-10a4 4 0 0 1 5.7-5.6Z"/><path d="m8 15 7-7"/></svg>',
  card: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18"/></svg>',
  file: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M6 2h8l4 4v16H6Z"/><path d="M14 2v5h5M9 13h6M9 17h6"/></svg>',
  location: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>',
  lock: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="4" y="10" width="16" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>'
};

function brand() { return '<div class="brand">res<span class="cross">+</span>paw</div>'; }
function avatar(src, alt = '', size = '') { return `<div class="avatar ${size}"><img src="${src}" alt="${alt}"></div>`; }
function header(title = '', opts = {}) {
  const back = opts.back === false ? '<span></span>' : `<button class="back-btn" data-back aria-label="Go back">${icons.back}</button>`;
  const right = opts.bell ? `<button class="icon-btn" data-route="notifications" aria-label="Notifications">${icons.bell}</button>` : (opts.right || '<span></span>');
  if (opts.brand) return `<header class="topbar centered">${back}${brand()}${right}</header>`;
  return `<header class="topbar">${back}<div class="grow"><h1 class="title">${title}</h1>${opts.subtitle ? `<p class="subtitle">${opts.subtitle}</p>` : ''}</div>${right}</header>`;
}
function shell(body, { tab = '', noNav = false, classes = '' } = {}) {
  return `<div class="screen-content ${noNav ? 'no-nav' : ''} ${classes}">${body}</div>${noNav ? '' : bottomNav(tab)}`;
}
function bottomNav(active) {
  const nav = [['home', 'Home', icons.home], ['find-care', 'Find care', icons.search], ['appointments', 'Appointments', icons.calendar], ['pets', 'Pets', icons.pet], ['profile', 'Profile', icons.user]];
  return `<nav class="bottom-nav" aria-label="Primary navigation">${nav.map(([r, l, i]) => `<button class="nav-item ${active === r ? 'active' : ''}" data-route="${r}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}</nav>`;
}
function status(text, type = '') { return `<span class="badge ${type}">${text}</span>`; }
function button(text, route, kind = 'primary', extra = '') { return `<button class="${kind}" ${route ? `data-route="${route}"` : ''} ${extra}>${text}</button>`; }
function listRow(icon, title, note, route, badge = '') { return `<button class="list-row" ${route ? `data-route="${route}"` : ''} style="width:100%;border-left:0;border-right:0;border-top:0;background:transparent;text-align:left"><span class="list-icon">${icon}</span><span class="grow"><strong>${title}</strong>${note ? `<span class="muted small" style="display:block;margin-top:2px">${note}</span>` : ''}</span>${badge}<span class="chev">›</span></button>`; }
function progress(step) { return `<div class="stepper">${[1, 2, 3, 4].map((n, i) => `${i ? '<span class="step-line"></span>' : ''}<span class="step ${n < step ? 'done' : n === step ? 'active' : ''}">${n < step ? '✓' : n}</span>`).join('')}</div>`; }
function sticky(content) { return `<div class="sticky-actions">${content}</div>`; }
function section(title, content, action = '') { return `<section class="section"><div class="section-head"><h2 class="section-title">${title}</h2>${action}</div>${content}</section>`; }
function vetCard(name, photo, specialty, rating, distance, route = 'vet') {
  return `<article class="card vet-card"><div class="media"><img src="${photo}" alt="${name}"></div><div><h3>${name}</h3><p class="muted tiny">${specialty}</p><p class="small" style="margin-top:7px"><span style="color:#eaa24a">★</span> <strong>${rating}</strong> <span class="muted">· ${distance}</span></p><span class="badge" style="margin-top:8px">Next: Today, 5:15 PM</span></div><button class="icon-btn" data-route="${route}" aria-label="View ${name}">›</button></article>`;
}
function appointmentCard(time, pet, vet, type, route = 'appointment') {
  return `<button class="card appointment-card" data-route="${route}" style="width:100%;text-align:left"><span class="time-block">${time}</span>${avatar(pet === 'Bruno' ? IMG.bruno : IMG.luna, pet, 'sm')}<span class="grow"><strong>${pet}</strong><span class="muted small" style="display:block">${vet}</span><span class="tiny" style="display:flex;gap:4px;margin-top:4px">${type === 'Video consultation' ? icons.video : icons.location} ${type}</span></span><span class="chev">›</span></button>`;
}

function renderSplash() { return `<div class="splash"><div class="splash-logo">res<span style="font-size:.65em">+</span>paw</div><p>Care for every paw</p><button class="secondary" style="margin-top:44px;border-color:#fff;color:#fff" data-route="welcome">Open prototype</button></div>`; }
function renderWelcome() { return `<div class="auth"><div class="auth-logo">${brand()}</div><h1 class="title">Welcome to Respaw</h1><p class="subtitle">Trusted care for every part of your pet’s life.</p><div class="media wide" style="margin:26px 0"><img src="${IMG.care}" alt="Happy dog"></div><div class="stack">${button('Sign in', 'sign-in', 'primary block')}${button('Continue with phone OTP', 'otp', 'secondary block')}${button('Create an account', 'create-account', 'ghost block')}</div></div>`; }
function renderSignIn() { return `<div class="auth"><div class="auth-logo">${brand()}</div><h1 class="title">Welcome back</h1><p class="subtitle">Sign in to continue caring for your pets.</p><form class="form" style="margin-top:28px" data-form="signin"><div class="field"><label>Email address</label><input class="input" type="email" value="priya@example.com" required></div><div class="field"><label>Password</label><input class="input" type="password" value="respaw123" required></div><button class="link-btn" type="button" data-route="reset-password">Forgot password?</button><button class="primary block" type="submit">Sign in</button></form><div class="divider"></div>${button('Sign in with phone OTP', 'otp', 'secondary block')}${button('Create account', 'create-account', 'ghost block')}<button class="link-btn" data-route="server-settings" style="margin:24px auto 0">Internal server settings</button></div>`; }
function renderOtp() { return shell(`${header('Phone OTP', { brand: true })}<h1 class="title">Verify your number</h1><p class="subtitle">We sent a six-digit code to +91 98765 43210.</p><div class="grid-3" style="grid-template-columns:repeat(6,1fr);margin-top:28px">${'542801'.split('').map(x => `<input class="input" value="${x}" inputmode="numeric" maxlength="1" style="padding:0;text-align:center;font-weight:800">`).join('')}</div><p class="muted small" style="margin-top:14px">Resend code in 00:24</p>${sticky(button('Verify and continue', 'home', 'primary block'))}`, { noNav: true }); }
function renderAccount() { return shell(`${header('Create account', { brand: true })}${progress(1)}<h2>Tell us about you</h2><form class="form" style="margin-top:18px" data-form="account"><div class="field"><label>Full name</label><input class="input" value="Priya Sharma" required></div><div class="field"><label>Email</label><input class="input" type="email" placeholder="you@example.com" required></div><div class="field"><label>Phone</label><input class="input" inputmode="tel" placeholder="+91 98765 43210"></div><div class="field"><label>Password</label><input class="input" type="password" required><span class="field-help">At least 8 characters with a number.</span></div><label class="small"><input type="checkbox" checked> I agree to the Terms and Privacy Policy</label></form>${sticky(button('Create my account', 'home', 'primary block', 'data-action="submit-account"'))}`, { noNav: true }); }
function renderReset() { return shell(`${header('Reset password', { brand: true })}<div class="empty" style="padding-top:24px"><div class="empty-mark">${icons.lock}</div><h2>Recover your account</h2><p class="muted small" style="margin-top:7px">Enter your email and we’ll send secure reset instructions.</p></div><div class="field"><label>Email address</label><input class="input" type="email" value="priya@example.com"></div>${sticky(button('Send reset link', '', 'primary block', 'data-action="reset-link"'))}`, { noNav: true }); }

function renderHome() {
  const care = state.careGiven ? ['Given today', 'Undo', 'completed'] : ['Due now', 'Mark as given', ''];
  return shell(`<header class="topbar"><div><h1 class="title">Good morning, Priya</h1><p class="subtitle">How is Bruno today?</p></div><button class="icon-btn" data-route="notifications">${icons.bell}</button></header><div class="row">${avatar(IMG.bruno, 'Bruno')}<div><h3>Bruno</h3><p class="muted small">Golden Retriever · 3 years</p></div></div><article class="hero" style="margin-top:22px"><span class="badge">Next appointment</span><div class="row" style="margin-top:14px"><div class="media square" style="width:70px"><img src="${IMG.ananya}" alt="Dr. Ananya Rao"></div><div class="grow"><h2>Dr. Ananya Rao</h2><p class="strong" style="color:var(--purple);margin-top:3px">Today, 4:30 PM</p><p class="muted small" style="margin-top:4px">${icons.video} Video consultation</p></div></div>${button('View details', 'appointment', 'primary block', 'style="margin-top:16px"')}</article><div class="quick-grid" style="margin-top:16px"><button class="quick" data-route="find-care">${icons.search}<span>Find a vet</span></button><button class="quick" data-route="modality">${icons.video}<span>Online consult</span></button><button class="quick" data-route="pet-health">${icons.file}<span>Records</span></button><button class="quick emergency" data-route="emergency">${icons.plus}<span>Emergency</span></button></div>${section('Care today', `<article class="card ${care[2] === 'completed' ? 'teal' : ''}"><div class="row"><span class="list-icon">${state.careGiven ? icons.check : icons.pill}</span><div class="grow"><span class="badge ${state.careGiven ? 'teal' : ''}">${care[0]}</span><h3 style="margin-top:4px">Bravecto Chewable</h3><p class="muted tiny">Flea & tick prevention · With food</p></div><button class="secondary" style="min-height:40px;padding:0 10px;font-size:10px" data-action="care">${care[1]}</button></div></article>`, `<button class="link-btn" data-route="medications">View all ›</button>`)}${section('Nearby vets', `<div class="stack">${vetCard('Dr. Meera Iyer', IMG.meera, 'Small animal practice', '4.7', '1.2 km')}${vetCard('Dr. Arjun Nair', IMG.arjun, 'Veterinary clinic', '4.6', '2.1 km')}</div>`, `<button class="link-btn" data-route="find-care">View all ›</button>`)}`, { tab: 'home' });
}

function renderNotifications() { return shell(`${header('Notifications', { bell: false, right: '<button class="link-btn" data-action="read-all">Mark all read</button>' })}<div class="chips"><button class="chip selected">All</button><button class="chip">Unread</button></div><p class="section-label" style="margin-top:22px">Today</p><div class="card ${state.notificationsRead ? '' : 'soft'}">${listRow(icons.calendar, 'Appointment confirmed', 'Dr. Ananya accepted Bruno’s video consultation.', 'appointment', state.notificationsRead ? '' : status('New'))}${listRow(icons.card, 'Payment received', '₹600 paid successfully.', 'payment-detail')}${listRow(icons.pill, 'Medication due', 'Bravecto is due at 4:30 PM.', 'medications')}</div><p class="section-label" style="margin-top:22px">Earlier</p><div class="card">${listRow(icons.file, 'New prescription', 'A prescription is ready to view.', 'prescriptions')}${listRow(icons.pet, 'Care tip for Bruno', 'Five ways to keep ears healthy.', 'article')}</div>`, { tab: 'home' }); }

function renderFindCare() { return shell(`${header('Find care', { back: false, bell: true })}<div class="searchbar">${icons.search}<input id="vetSearch" placeholder="Search clinics, vets, services…"><button class="icon-btn" data-route="search-filters" style="width:38px;height:38px">☰</button></div><div class="chips" style="margin-top:12px"><button class="chip selected" data-filter="All">All</button><button class="chip" data-filter="Available today">Available today</button><button class="chip" data-filter="Online">Online</button><button class="chip danger" data-filter="Emergency">Emergency</button></div><div class="section-head" style="margin-top:22px"><p><strong>24 vets</strong> <span class="muted small">near Koramangala</span></p><button class="link-btn" data-route="map">Map view</button></div><div class="stack">${vetCard('Dr. Meera Iyer', IMG.meera, 'Small animal practice · ₹600', '4.7', '1.2 km')}${vetCard('Dr. Arjun Nair', IMG.arjun, 'Veterinary clinic · ₹700', '4.6', '1.8 km')}${vetCard('Dr. Ananya Rao', IMG.ananya, 'General & online care · ₹550', '4.9', '2.4 km')}</div>`, { tab: 'find-care' }); }
function renderFilters() { return shell(`${header('Filter vets', { brand: true })}<div class="form"><div><p class="section-label">Availability</p><div class="chips"><button class="chip selected">Available today</button><button class="chip">Available now</button><button class="chip">This week</button></div></div><div><p class="section-label">Care type</p><div class="chips"><button class="chip selected">Clinic</button><button class="chip">Online</button><button class="chip">Home visit</button><button class="chip danger">Emergency</button></div></div><div class="field"><label>Maximum distance: <strong>10 km</strong></label><input type="range" min="1" max="50" value="10" style="accent-color:var(--purple)"></div><div><p class="section-label">Speciality</p><div class="chips"><button class="chip selected">General</button><button class="chip">Dermatology</button><button class="chip">Dental</button><button class="chip">Surgery</button></div></div><div><p class="section-label">Minimum rating</p><div class="chips"><button class="chip">Any</button><button class="chip selected">4+ stars</button><button class="chip">4.5+ stars</button></div></div></div>${sticky(`<div class="grid-2">${button('Reset', '', 'secondary block', 'data-action="reset-filters"')}${button('Show 18 vets', 'find-care', 'primary block')}</div>`)}`, { noNav: true }); }
function renderMap() { return `<div class="fullscreen">${shell(`${header('Nearby vets', { back: true })}<div class="searchbar" style="position:absolute;z-index:4;left:18px;right:18px;top:82px">${icons.search}<span class="muted">Search this area</span><button class="chip selected" data-route="find-care">List</button></div>`, { noNav: true })}<div class="map" style="margin-top:-72px"><span class="pin" style="left:18%;top:32%"><span>●</span></span><span class="pin" style="left:58%;top:22%"><span>●</span></span><span class="pin" style="left:70%;top:48%"><span>●</span></span><span class="pin" style="left:35%;top:58%"><span>●</span></span><div class="map-card">${vetCard('Dr. Meera Iyer', IMG.meera, 'Small animal practice', '4.7', '1.2 km')}</div></div>${bottomNav('find-care')}</div>`; }
function renderVet() { return shell(`${header('', { brand: true, right: '<button class="icon-btn" data-toast="More actions">•••</button>' })}<div class="row">${avatar(IMG.meera, 'Dr. Meera Iyer', 'lg')}<div class="grow"><div class="row"><h1 style="font-size:24px">Dr. Meera Iyer</h1>${status('Verified')}</div><p class="muted small">BVSc & AH, MVSc · Small Animal Practice</p><p style="margin-top:6px"><span style="color:#eaa24a">★</span> <strong>4.7</strong> <button class="link-btn" data-route="reviews">128 reviews</button></p></div></div><div class="stats card soft" style="margin-top:18px"><div class="stat"><strong>8 yrs</strong><span>Experience</span></div><div class="stat"><strong>98%</strong><span>Pet rating</span></div><div class="stat"><strong>3</strong><span>Languages</span></div></div>${section('About', `<p class="muted small">Compassionate veterinarian focused on preventive care, diagnostics, dermatology, and internal medicine.</p>`)}${section('Services', `<div class="chips"><span class="chip selected">General consultation</span><span class="chip">Vaccination</span><span class="chip">Diagnostics</span><span class="chip">Dermatology</span></div>`)}${section('Fees & availability', `<div class="card meta-list"><div class="meta-row"><span>Clinic consultation</span><strong>₹600</strong></div><div class="meta-row"><span>Online consultation</span><strong>₹450</strong></div><div class="meta-row"><span>Availability</span>${status('Today', 'teal')}</div><div class="meta-row"><span>Next slot</span><strong style="color:var(--purple)">5:15 PM</strong></div></div>`)}${section('Clinic location', `<div class="callout">${icons.location}<div><strong>Paws & Claws Clinic</strong><p class="muted tiny">Koramangala, Bengaluru · 1.2 km</p></div></div>`)}${sticky(`<div class="grid-2">${button('Consult online', 'modality', 'secondary block')}${button('Book appointment', 'booking-pet', 'primary block')}</div>`)}`, { noNav: true }); }
function renderReviews() { return shell(`${header('Reviews', { brand: true })}<div class="row card soft"><div class="price">4.7</div><div class="grow"><div style="color:#eaa24a;font-size:20px">★★★★★</div><p class="muted small">128 verified reviews</p></div></div><div class="chips" style="margin-top:18px"><button class="chip selected">All</button><button class="chip">5 stars</button><button class="chip">4 stars</button><button class="chip">Most recent</button></div>${section('Pet parent reviews', `<div class="stack"><article class="card"><div class="row between"><strong>Nisha & Coco</strong><span style="color:#eaa24a">★★★★★</span></div><p class="muted small" style="margin-top:8px">Dr. Meera explained everything clearly and made Coco comfortable.</p><p class="faint tiny" style="margin-top:7px">Visited 12 May 2026</p></article><article class="card"><div class="row between"><strong>Rahul & Max</strong><span style="color:#eaa24a">★★★★★</span></div><p class="muted small" style="margin-top:8px">Excellent follow-up and thoughtful advice.</p></article></div>`)}`, { noNav: true }); }

function renderBookingPet() { return shell(`${header('', { brand: true })}${progress(1)}<h1 class="title">Book appointment</h1><p class="subtitle">Step 1 of 4 · Choose pet and visit type</p>${section('Your vet', vetCard('Dr. Meera Iyer', IMG.meera, 'Small animal practice', '4.7', '1.2 km'))}${section('Select pet', `<div class="grid-2"><button class="option-card selected" data-select-pet="Bruno"><div>${avatar(IMG.bruno, 'Bruno')}<strong style="display:block;margin-top:8px">Bruno</strong><span class="tiny muted">Golden Retriever</span></div><span class="radio"></span></button><button class="option-card" data-select-pet="Luna"><div>${avatar(IMG.luna, 'Luna')}<strong style="display:block;margin-top:8px">Luna</strong><span class="tiny muted">Indie Cat</span></div><span class="radio"></span></button></div>`)}${section('Select visit type', `<div class="stack"><button class="option-card selected" data-select-type="Clinic visit"><span class="list-icon">${icons.location}</span><span><strong>Clinic visit</strong><span class="muted tiny" style="display:block">In-person consultation · ₹600</span></span><span class="radio"></span></button><button class="option-card" data-select-type="Home visit"><span class="list-icon">${icons.home}</span><span><strong>Home visit</strong><span class="muted tiny" style="display:block">Vet comes to your home · ₹900</span></span><span class="radio"></span></button><button class="option-card" data-select-type="Online consult"><span class="list-icon">${icons.video}</span><span><strong>Online consult</strong><span class="muted tiny" style="display:block">Video care from anywhere · ₹450</span></span><span class="radio"></span></button></div>`)}${sticky(button('Continue', 'booking-time', 'primary block'))}`, { noNav: true }); }
function renderBookingTime() { const dates = [['Today', '24'], ['Sun', '25'], ['Mon', '26'], ['Tue', '27'], ['Wed', '28'], ['Thu', '29'], ['Fri', '30']]; const slots = ['9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '12:00 PM', '1:00 PM', '2:00 PM', '4:30 PM', '5:15 PM', '6:00 PM', '6:30 PM', '7:00 PM']; return shell(`${header('', { brand: true })}${progress(2)}<h1 class="title">Choose date & time</h1><p class="subtitle">Times are shown in your local time (IST).</p>${section('Select date', `<div class="date-strip">${dates.map((d, i) => `<button class="date ${i === 0 ? 'selected' : ''}" data-date="${d.join(' ')}"><span class="tiny">${d[0]}</span><strong style="display:block;font-size:16px">${d[1]}</strong><span class="tiny">May</span></button>`).join('')}</div>`)}${['Morning', 'Afternoon', 'Evening'].map((g, gi) => section(g, `<div class="slot-grid">${slots.slice(gi * 4, gi * 4 + 4).map(s => `<button class="slot ${s === state.booking.time ? 'selected' : ''}" data-slot="${s}">${s}</button>`).join('')}</div>`)).join('')}<div class="callout">${icons.calendar}<span class="muted small">Need a later date? Open the full calendar.</span></div>${sticky(button('Continue', 'booking-reason', 'primary block'))}`, { noNav: true }); }
function renderBookingReason() { return shell(`${header('', { brand: true })}${progress(3)}<h1 class="title">What brings you in?</h1><p class="subtitle">Share enough context to help the vet prepare.</p><div class="chips" style="margin-top:22px"><button class="chip selected">Routine check-up</button><button class="chip">Skin or coat</button><button class="chip">Vaccination</button><button class="chip">Digestive issue</button><button class="chip">Other</button></div><div class="field" style="margin-top:22px"><label>Reason for visit</label><textarea id="reasonInput">${state.booking.reason}</textarea><span class="field-help">Optional · 500 characters maximum</span></div><div class="callout" style="margin-top:16px">${icons.file}<div><strong>Bruno’s records will be available</strong><p class="muted tiny">The vet can review shared health information.</p></div></div>${sticky(button('Review booking', 'booking-review', 'primary block'))}`, { noNav: true }); }
function renderBookingReview() { return shell(`${header('', { brand: true })}${progress(4)}<h1 class="title">Review your appointment</h1><div class="card meta-list" style="margin-top:20px"><div class="meta-row"><span>Vet</span><strong>Dr. Meera Iyer</strong></div><div class="meta-row"><span>Pet</span><strong>${state.booking.pet}</strong></div><div class="meta-row"><span>Visit type</span><strong>${state.booking.type}</strong></div><div class="meta-row"><span>Date & time</span><strong>${state.booking.date}<br>${state.booking.time}</strong></div><div class="meta-row"><span>Reason</span><strong>${state.booking.reason}</strong></div></div>${section('Payment summary', `<div class="receipt"><div class="receipt-row"><span class="muted">Consultation fee</span><strong>₹600</strong></div><div class="receipt-row"><span class="muted">Convenience fee</span><strong>₹0</strong></div><div class="receipt-row total"><span>Total</span><span style="color:var(--purple)">₹600</span></div></div>`)}<div class="callout" style="margin-top:20px">${icons.lock}<p class="muted tiny">Cancel or reschedule up to 2 hours before the appointment. Fees may depend on clinic policy.</p></div>${sticky(button('Pay ₹600 securely', 'payment', 'primary block'))}`, { noNav: true }); }
function renderPayment() { return shell(`${header('Payment', { brand: true })}<div class="card soft"><div class="row">${avatar(IMG.meera, 'Dr. Meera', 'sm')}<div><strong>Dr. Meera Iyer</strong><p class="muted tiny">${state.booking.pet} · ${state.booking.date}, ${state.booking.time}</p></div></div></div>${section('Amount due', `<div class="receipt card"><div class="receipt-row"><span>Consultation</span><strong>₹600</strong></div><div class="receipt-row"><span>Taxes & fees</span><strong>₹0</strong></div><div class="receipt-row total"><span>Total</span><span>₹600</span></div></div>`)}${section('Payment method', `<button class="option-card selected"><span class="list-icon">${icons.card}</span><span class="grow"><strong>Razorpay secure checkout</strong><span class="muted tiny" style="display:block">UPI, cards and netbanking</span></span><span class="radio"></span></button>`)}<div class="callout" style="margin-top:20px">${icons.lock}<p class="muted tiny">Your payment details are handled securely by Razorpay.</p></div>${sticky(button('Pay ₹600 securely', '', 'primary block', 'data-action="pay"'))}`, { noNav: true }); }
function renderConfirmation() { return shell(`${header('', { brand: true, back: false })}<div class="success-mark">${icons.check}</div><div style="text-align:center"><h1 class="title">${state.booking.pet}’s appointment is confirmed</h1><p class="subtitle">We look forward to seeing you today.</p></div><div class="card meta-list" style="margin-top:24px"><div class="meta-row"><span>Vet</span><strong>Dr. Meera Iyer</strong></div><div class="meta-row"><span>Pet</span><strong>${state.booking.pet}</strong></div><div class="meta-row"><span>Visit</span><strong>${state.booking.type}</strong></div><div class="meta-row"><span>When</span><strong>${state.booking.date}<br>${state.booking.time}</strong></div></div><div class="card teal" style="margin-top:14px"><div class="row between"><span>Amount paid</span><strong class="price">₹600</strong></div></div>${section('What’s next?', `<div class="stack small"><p>• Arrive 10 minutes early for a smooth check-in.</p><p>• Bring previous medical records if available.</p><p>• You’ll receive a reminder before the appointment.</p></div>`)}${sticky(`<div class="stack">${button('View appointment', 'appointment', 'primary block')}${button('Back to home', 'home', 'secondary block')}</div>`)}`, { noNav: true }); }

function renderAppointments() { return shell(`${header('Appointments', { back: false, bell: true })}<div class="hero"><span class="badge">Next appointment</span><div class="row" style="margin-top:12px">${avatar(IMG.bruno, 'Bruno')}<div class="grow"><h3>Bruno</h3><p class="strong" style="color:var(--purple)">Today, 4:30 PM</p><p class="muted tiny">Dr. Ananya Rao · Video consultation</p></div><button class="icon-btn" data-route="appointment">›</button></div></div><div class="segment" style="margin-top:16px">${['Upcoming', 'Past', 'Cancelled'].map(x => `<button class="${state.appointmentTab === x ? 'active' : ''}" data-appt-tab="${x}">${x}</button>`).join('')}</div>${section('Today', appointmentCard('4:30 PM', 'Bruno', 'Dr. Ananya Rao', 'Video consultation'))}${section('Tomorrow', appointmentCard('11:00 AM', 'Luna', 'Dr. Meera Iyer', 'Clinic visit'))}${state.appointmentTab === 'Past' ? section('Earlier', appointmentCard('20 May', 'Bruno', 'Dr. Ananya Rao', 'Video consultation')) : ''}`, { tab: 'appointments' }); }
function renderAppointment() { return shell(`${header('', { brand: true, right: status('Confirmed', 'teal') })}<div class="card soft"><div class="row between"><div style="text-align:center">${avatar(IMG.ananya, 'Dr. Ananya', 'lg')}<strong style="display:block;margin-top:6px">Dr. Ananya Rao</strong></div>${icons.video}<div style="text-align:center">${avatar(IMG.bruno, 'Bruno', 'lg')}<strong style="display:block;margin-top:6px">Bruno</strong></div></div></div>${section('Status', `<div class="timeline"><div class="timeline-item done"><span class="timeline-dot"></span><strong>Appointment booked</strong><p class="muted tiny">20 May · 9:41 AM</p></div><div class="timeline-item done"><span class="timeline-dot"></span><strong>Payment completed</strong><p class="muted tiny">₹600 paid securely</p></div><div class="timeline-item active"><span class="timeline-dot"></span><strong>Appointment confirmed</strong><p class="muted tiny">Join 5 minutes before start</p></div></div>`)}${section('Consultation details', `<div class="card soft meta-list"><div class="meta-row"><span>Date & time</span><strong>Today · 4:30 PM</strong></div><div class="meta-row"><span>Type</span><strong>Video consultation</strong></div><div class="meta-row"><span>Reason</span><strong>Skin irritation</strong></div></div>`)}${section('Payment', `<button class="card row between" data-route="payment-detail" style="width:100%"><span>Paid securely</span><strong>₹600 ›</strong></button>`)}${sticky(`<div class="grid-2">${button('Reschedule', 'reschedule', 'secondary block')}${button('Cancel', 'cancel', 'secondary red block')}</div>${button('Join consultation', 'device-check', 'primary block', 'style="margin-top:10px"')}`)}`, { noNav: true }); }
function renderReschedule() { return shell(`${header('Reschedule', { brand: true })}<div class="callout"><strong>Current:</strong><span class="muted small">Today, 4:30 PM</span></div>${section('Choose a new date', `<div class="date-strip">${['25', '26', '27', '28', '29', '30', '31'].map((d, i) => `<button class="date ${i === 1 ? 'selected' : ''}"><span class="tiny">${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][i]}</span><strong style="display:block">${d}</strong></button>`).join('')}</div>`)}${section('Available times', `<div class="slot-grid">${['9:00 AM', '10:30 AM', '12:00 PM', '2:30 PM', '4:00 PM', '5:15 PM'].map((s, i) => `<button class="slot ${i === 5 ? 'selected' : ''}">${s}</button>`).join('')}</div>`)}${sticky(button('Confirm new time', 'appointment', 'primary block', 'data-toast="Appointment rescheduled"'))}`, { noNav: true }); }
function renderCancel() { return shell(`${header('Cancel appointment', { brand: true })}<div class="card danger"><h3>Cancel Bruno’s appointment?</h3><p class="muted small" style="margin-top:6px">Your video consultation with Dr. Ananya Rao is today at 4:30 PM.</p></div><div class="field" style="margin-top:22px"><label>Reason for cancellation</label><select><option>Schedule conflict</option><option>Pet is feeling better</option><option>Booked by mistake</option><option>Other</option></select></div><div class="field" style="margin-top:14px"><label>Additional details</label><textarea placeholder="Optional"></textarea></div><div class="callout" style="margin-top:18px"><p class="muted small">Refunds are returned to the original payment method based on clinic policy.</p></div>${sticky(`<div class="stack">${button('Keep appointment', 'appointment', 'primary block')}${button('Confirm cancellation', 'appointments', 'danger-btn block', 'data-toast="Appointment cancelled"')}</div>`)}`, { noNav: true }); }
function renderReview() { return shell(`${header('Rate your visit', { brand: true })}<div class="row card soft">${avatar(IMG.ananya, 'Dr. Ananya')}<div><h3>Dr. Ananya Rao</h3><p class="muted small">Bruno · Video consultation</p></div></div><div style="text-align:center;margin:30px 0"><p class="strong">How was your experience?</p><div style="font-size:42px;color:#eaa24a;letter-spacing:5px;margin-top:8px">★★★★★</div></div><div class="field"><label>Share more (optional)</label><textarea placeholder="What went well? What could be better?"></textarea></div>${sticky(button('Submit review', 'appointment', 'primary block', 'data-toast="Review submitted"'))}`, { noNav: true }); }

function renderModality() { return shell(`${header('Start a consultation', { brand: true })}<p class="subtitle">Choose how you’d like to connect with a vet.</p><div class="stack" style="margin-top:24px"><button class="option-card selected" data-modality="Video"><span class="list-icon">${icons.video}</span><span class="grow"><strong>Video consultation</strong><span class="muted tiny" style="display:block">Best for visual symptoms · ₹450</span></span><span class="radio"></span></button><button class="option-card" data-modality="Audio"><span class="list-icon">◖</span><span class="grow"><strong>Audio consultation</strong><span class="muted tiny" style="display:block">Talk without video · ₹350</span></span><span class="radio"></span></button><button class="option-card" data-modality="Chat"><span class="list-icon">◌</span><span class="grow"><strong>Chat consultation</strong><span class="muted tiny" style="display:block">Message a vet · ₹250</span></span><span class="radio"></span></button></div><div class="card danger" style="margin-top:22px"><strong>Not for life-threatening emergencies</strong><p class="muted tiny" style="margin-top:5px">Use emergency care if your pet has trouble breathing, severe bleeding, collapse, or seizures.</p><button class="link-btn sos" data-route="emergency">Find emergency care</button></div>${sticky(button('Continue with video', 'device-check', 'primary block'))}`, { noNav: true }); }
function renderDeviceCheck() { return shell(`${header('Device check', { brand: true })}<div class="media wide" style="background:#2b1938"><img src="${IMG.priya}" alt="Camera preview" style="opacity:.9"></div><div class="stack" style="margin-top:18px"><div class="card row"><span class="list-icon">${icons.video}</span><div class="grow"><strong>Camera</strong><p class="muted tiny">Working correctly</p></div>${status('Ready', 'teal')}</div><div class="card row"><span class="list-icon">◖</span><div class="grow"><strong>Microphone</strong><p class="muted tiny">We can hear you</p></div>${status('Ready', 'teal')}</div><div class="card row"><span class="list-icon">↯</span><div class="grow"><strong>Connection</strong><p class="muted tiny">Stable for video</p></div>${status('Good', 'teal')}</div></div><p class="muted tiny" style="margin-top:18px">Your camera and microphone are used only during the consultation.</p>${sticky(button('Join consultation', 'consultation', 'primary block'))}`, { noNav: true }); }
function renderConsultation() { return `<div class="video-room"><div class="row between"><button class="back-btn" data-route="appointment" style="color:#fff">${icons.back}</button><div class="video-top"><h3>Dr. Ananya Rao</h3><p class="tiny">Bruno · <span style="color:#59d5b7">● Connected</span> · 04:32</p></div><span style="width:44px"></span></div><div class="video-stage"><img src="${IMG.ananya}" alt="Dr. Ananya Rao on video"><div class="self-view"><img src="${IMG.priya}" alt="Your camera preview"></div></div><div class="call-controls"><button class="call-control" data-call="mic" aria-label="Toggle microphone">◖</button><button class="call-control" data-call="camera" aria-label="Toggle camera">▣</button><button class="call-control" data-route="consultation-chat" aria-label="Open chat">●</button><button class="call-control end" data-action="end-call" aria-label="End call">⌁</button></div></div>`; }
function renderConsultChat() { return shell(`${header('Dr. Ananya Rao', { brand: true, right: status('Connected', 'teal') })}<div class="chat"><div class="bubble">Hi Priya, I’ve reviewed Bruno’s notes. Can you show me the irritated area?</div><div class="bubble me">Yes, it’s just behind his left ear.</div><div class="bubble">Thank you. I’ll guide you through a closer check.</div></div><div class="composer"><input id="consultInput" placeholder="Message Dr. Ananya…"><button data-action="send-consult">➤</button></div>`, { noNav: true }); }
function renderVisitSummary() { return shell(`${header('Visit summary', { brand: true })}<div class="card soft row">${avatar(IMG.ananya, 'Dr. Ananya')}<div><h3>Dr. Ananya Rao</h3><p class="muted tiny">Video consultation · Completed today</p></div>${status('Completed', 'teal')}</div>${section('Diagnosis', `<div class="card"><strong>Mild allergic dermatitis</strong><p class="muted small" style="margin-top:6px">No signs of infection. Monitor for increased redness or discharge.</p></div>`)}${section('Care plan', `<div class="card meta-list"><div class="meta-row"><span>Clean affected area</span><strong>Twice daily</strong></div><div class="meta-row"><span>Medication</span><strong>Cetirizine 5 mg</strong></div><div class="meta-row"><span>Follow-up</span><strong>In 7 days</strong></div></div>`)}${section('Prescription', listRow(icons.file, 'Prescription PDF', 'Issued today', 'prescriptions'))}${sticky(`<div class="grid-2">${button('Add reminder', 'reminder-edit', 'secondary block')}${button('Rate consultation', 'review', 'primary block')}</div>`)}`, { noNav: true }); }
function renderAssistant() { return shell(`${header('AI Pet Assistant', { brand: true, right: status('Online', 'teal') })}<p class="subtitle">General pet-care guidance, available anytime.</p><div class="chips" style="margin-top:16px"><button class="chip" data-prompt="My pet isn’t eating">Not eating</button><button class="chip" data-prompt="Itchy skin in dogs">Itchy skin</button><button class="chip" data-prompt="Traveling with pets">Travel tips</button></div><div class="chat" id="assistantMessages" style="margin-top:22px">${state.messages.map(m => `<div class="bubble ${m.from === 'me' ? 'me' : ''}">${m.text}</div>`).join('')}</div><div class="callout" style="margin-top:18px"><span>ⓘ</span><p class="muted tiny">General guidance only, not a diagnosis. For urgent concerns, consult a vet.</p></div><div class="composer"><input id="assistantInput" placeholder="Ask anything about your pet…"><button data-action="send-assistant">➤</button></div>`, { noNav: true }); }

function renderPets() { return shell(`${header('Your pets', { back: false, bell: true })}<button class="link-btn" data-route="pet-edit" style="position:absolute;right:20px;top:70px">${icons.plus} Add pet</button><article class="pet-feature"><div class="row">${avatar(IMG.bruno, 'Bruno', 'lg')}<div class="grow"><h2>Bruno</h2><p class="muted small">Golden Retriever · 3 years</p>${status('Primary pet')}</div><button class="icon-btn" data-route="pet-health">›</button></div><div class="stats"><div class="stat"><strong>4:30 PM</strong><span>Next care</span></div><div class="stat"><strong>28.5 kg</strong><span>Weight</span></div><div class="stat"><strong>Up to date</strong><span>Vaccines</span></div></div></article><article class="card row" style="margin-top:16px">${avatar(IMG.luna, 'Luna')}<div class="grow"><h3>Luna</h3><p class="muted small">Indie Cat · 2 years</p></div><button class="icon-btn" data-route="pet-health">›</button></article>${section('Next care', `<div class="card row"><span class="list-icon">${icons.pill}</span><div class="grow"><span class="badge">Due now</span><h3 style="margin-top:3px">Bravecto Chewable</h3><p class="muted tiny">Bruno · With food</p></div><button class="secondary" data-action="care" style="min-height:40px;padding:0 10px;font-size:10px">${state.careGiven ? 'Undo' : 'Mark as given'}</button></div>`, `<button class="link-btn" data-route="medications">View all ›</button>`)}`, { tab: 'pets' }); }
function renderPetEdit() { return shell(`${header('Add / edit pet', { brand: true })}<div style="display:grid;place-items:center;margin:10px 0 24px">${avatar(IMG.bruno, 'Bruno', 'lg')}<button class="link-btn" data-toast="Photo picker opened">Change photo</button></div><form class="form"><p class="section-label">Basics</p><div class="field"><label>Name</label><input class="input" value="Bruno"></div><div class="field"><label>Species</label><select><option>Dog</option><option>Cat</option><option>Bird</option></select></div><div class="field"><label>Breed</label><input class="input" value="Golden Retriever"></div><div class="field"><label>Date of birth</label><input class="input" type="date" value="2023-05-24"></div><div class="grid-2"><div class="field"><label>Weight</label><input class="input" value="28.5 kg"></div><div class="field"><label>Sex</label><select><option>Male</option><option>Female</option></select></div></div><p class="section-label" style="margin-top:8px">Health notes</p><div class="field"><label>Allergies or conditions</label><textarea placeholder="Optional">Seasonal skin sensitivity</textarea></div></form>${sticky(button('Save changes', 'pets', 'primary block', 'data-toast="Bruno’s profile saved"'))}`, { noNav: true }); }
function petHeader() { return `<div class="row">${avatar(IMG.bruno, 'Bruno')}<div class="grow"><h1 class="title">Bruno</h1><p class="muted small">Golden Retriever · 3 years</p></div><button class="icon-btn" data-route="pet-edit">✎</button></div><div class="stats" style="margin-top:18px"><div class="stat"><strong>24 May 2023</strong><span>Born</span></div><div class="stat"><strong>28.5 kg</strong><span>Weight</span></div><div class="stat"><strong>Male</strong><span>Sex</span></div></div>`; }
function recordTabs(active) { return `<div class="tabs" style="margin-top:20px">${[['Timeline', 'pet-health'], ['Medical', 'timeline'], ['Medications', 'medications'], ['Reminders', 'reminders']].map(([x, r]) => `<button class="${active === x ? 'active' : ''}" data-route="${r}">${x}</button>`).join('')}</div>`; }
function renderPetHealth() { return shell(`${header('', { brand: true, bell: true })}${petHeader()}${recordTabs('Timeline')}<div class="card soft row" style="margin-top:16px"><span class="list-icon">${icons.calendar}</span><div class="grow"><span class="badge">Next up · Today 4:30 PM</span><h3>Dr. Ananya Rao</h3><p class="muted tiny">Video consultation</p></div><span class="chev">›</span></div>${section('May 2026', `<div class="timeline"><div class="timeline-item active"><span class="timeline-dot"></span><strong>Clinic visit</strong><p class="muted tiny">24 May · Dr. Ananya Rao</p></div><div class="timeline-item done"><span class="timeline-dot"></span><strong>Bravecto given</strong><p class="muted tiny">18 May · Flea & tick prevention</p></div><div class="timeline-item done"><span class="timeline-dot"></span><strong>Annual health certificate</strong><p class="muted tiny">2 May · Paws & Claws Clinic</p></div></div>`)}<button class="primary" data-action="add-menu" style="position:absolute;right:20px;bottom:106px;width:54px;height:54px;border-radius:50%;padding:0">${icons.plus}</button>`, { tab: 'pets' }); }
function renderTimeline() { return shell(`${header('', { brand: true })}${petHeader()}${recordTabs('Medical')}<div class="chips" style="margin-top:16px"><button class="chip selected">All records</button><button class="chip">Vaccines</button><button class="chip">Visits</button><button class="chip">Documents</button></div>${section('Medical timeline', `<div class="timeline"><div class="timeline-item active"><span class="timeline-dot"></span><strong>Allergic dermatitis consultation</strong><p class="muted tiny">Today · Dr. Ananya Rao</p><button class="link-btn" data-route="medical-record">View record</button></div><div class="timeline-item done"><span class="timeline-dot"></span><strong>Rabies vaccination</strong><p class="muted tiny">10 Mar · Next due 10 Mar 2027</p></div><div class="timeline-item done"><span class="timeline-dot"></span><strong>Annual blood panel</strong><p class="muted tiny">18 Jan · Results normal</p></div></div>`)}${sticky(button('Add medical record', 'medical-record', 'primary block'))}`, { noNav: true }); }
function renderMedicalRecord() { return shell(`${header('Medical record', { brand: true })}<div class="card soft"><span class="badge teal">Consultation record</span><h2 style="margin-top:8px">Allergic dermatitis</h2><p class="muted small">24 May 2026 · Dr. Ananya Rao</p></div>${section('Clinical notes', `<p class="muted small">Mild inflammation behind the left ear. No infection or discharge observed.</p>`)}${section('Treatment', `<div class="card meta-list"><div class="meta-row"><span>Medicine</span><strong>Cetirizine 5 mg</strong></div><div class="meta-row"><span>Frequency</span><strong>Once daily</strong></div><div class="meta-row"><span>Duration</span><strong>5 days</strong></div></div>`)}${section('Attachments', listRow(icons.file, 'Visit prescription', 'PDF · 246 KB', 'prescriptions'))}${sticky(`<div class="grid-2">${button('Add reminder', 'reminder-edit', 'secondary block')}${button('Add medication', 'medication-edit', 'primary block')}</div>`)}`, { noNav: true }); }
function renderMedications() { return shell(`${header('', { brand: true })}${recordTabs('Medications')}${section('Due today', `<div class="card ${state.careGiven ? 'teal' : 'soft'} row"><span class="list-icon">${state.careGiven ? icons.check : icons.pill}</span><div class="grow"><h3>Bravecto Chewable</h3><p class="muted tiny">Bruno · With food · 4:30 PM</p></div><button class="secondary" data-action="care" style="min-height:40px;padding:0 10px;font-size:10px">${state.careGiven ? 'Undo' : 'Mark as given'}</button></div>`)}${section('Active medications', `<div class="card">${listRow(icons.pill, 'Cetirizine 5 mg', 'Once daily · 4 days remaining', 'medication-edit', status('Active', 'teal'))}${listRow(icons.pill, 'NexGard Chewable', 'Monthly · Next 24 Jun', 'medication-edit', status('Scheduled'))}</div>`)}${section('Adherence', `<div class="card row"><div class="progress-ring">100%</div><div><h3>Great job!</h3><p class="muted small">Bruno is up to date on medications.</p></div></div>`)}${sticky(button('Add medication', 'medication-edit', 'primary block'))}`, { noNav: true }); }
function renderMedicationEdit() { return shell(`${header('Add medication', { brand: true })}<form class="form"><div class="field"><label>Medication name</label><input class="input" value="Cetirizine"></div><div class="grid-2"><div class="field"><label>Dosage</label><input class="input" value="5"></div><div class="field"><label>Unit</label><select><option>mg</option><option>ml</option></select></div></div><div class="field"><label>Frequency</label><select><option>Once daily</option><option>Twice daily</option><option>Weekly</option></select></div><div class="field"><label>Start date</label><input class="input" type="date" value="2026-05-24"></div><div class="field"><label>Time</label><input class="input" type="time" value="16:30"></div><div class="field"><label>Instructions</label><textarea>Give with food.</textarea></div></form>${sticky(button('Save medication', 'medications', 'primary block', 'data-toast="Medication saved"'))}`, { noNav: true }); }
function renderReminders() { return shell(`${header('', { brand: true })}${recordTabs('Reminders')}${section('Due today', `<div class="card amber row"><span class="list-icon">${icons.calendar}</span><div class="grow"><h3>Bravecto dose</h3><p class="muted tiny">Today · 4:30 PM · Bruno</p></div><button class="secondary" data-toast="Reminder completed" style="min-height:40px">Complete</button></div>`)}${section('Upcoming', `<div class="card">${listRow(icons.calendar, 'NexGard dose', '24 Jun · Monthly', 'reminder-edit', status('31 days', 'amber'))}${listRow(icons.calendar, 'Rabies vaccination', '10 Mar 2027 · Bruno', 'reminder-edit', status('291 days', 'amber'))}</div>`)}${section('Completed', `<div class="card">${listRow(icons.check, 'Annual check-up', 'Completed 20 May', '', '')}</div>`)}${sticky(button('Add reminder', 'reminder-edit', 'primary block'))}`, { noNav: true }); }
function renderReminderEdit() { return shell(`${header('Add reminder', { brand: true })}<form class="form"><div class="field"><label>Reminder title</label><input class="input" value="Bravecto dose"></div><div class="field"><label>Pet</label><select><option>Bruno</option><option>Luna</option></select></div><div class="field"><label>Type</label><select><option>Medication</option><option>Vaccination</option><option>Appointment</option></select></div><div class="grid-2"><div class="field"><label>Date</label><input class="input" type="date" value="2026-06-24"></div><div class="field"><label>Time</label><input class="input" type="time" value="16:30"></div></div><div class="field"><label>Repeat</label><select><option>Monthly</option><option>Never</option><option>Weekly</option></select></div><div class="field"><label>Notes</label><textarea>Give with food.</textarea></div></form>${sticky(button('Save reminder', 'reminders', 'primary block', 'data-toast="Reminder saved"'))}`, { noNav: true }); }
function renderPrescriptions() { return shell(`${header('Prescriptions', { brand: true })}<div class="chips"><button class="chip selected">All pets</button><button class="chip">Bruno</button><button class="chip">Luna</button></div>${section('May 2026', `<div class="stack"><article class="card"><div class="row">${avatar(IMG.bruno, 'Bruno', 'sm')}<div class="grow"><h3>Allergic dermatitis</h3><p class="muted tiny">Dr. Ananya Rao · 24 May</p></div>${status('New')}</div><div class="divider"></div><p class="small"><strong>Cetirizine 5 mg</strong> · Once daily for 5 days</p><div class="grid-2" style="margin-top:14px">${button('View visit', 'medical-record', 'secondary block')}${button('Download', '', 'primary block', 'data-toast="Prescription downloaded"')}</div></article><article class="card"><div class="row">${avatar(IMG.luna, 'Luna', 'sm')}<div><h3>Routine vaccination</h3><p class="muted tiny">Dr. Meera Iyer · 8 May</p></div></div></article></div>`)} `, { noNav: true }); }
function renderDocuments() { return shell(`${header('Documents', { brand: true })}<div class="chips"><button class="chip selected">All</button><button class="chip">Lab reports</button><button class="chip">Certificates</button></div>${section('Bruno’s documents', `<div class="card">${listRow(icons.file, 'Annual health certificate', 'PDF · 1.2 MB · 2 May', '', status('Verified', 'teal'))}${listRow(icons.file, 'Blood panel results', 'PDF · 860 KB · 18 Jan', '')}${listRow(icons.file, 'Vaccination card', 'Image · 2.4 MB · 10 Mar', '')}</div>`)}${sticky(button('Upload document', '', 'primary block', 'data-toast="Upload picker opened"'))}`, { noNav: true }); }

function transactionRows() { return `<div class="card">${listRow(icons.calendar, 'Dr. Ananya Rao', 'Clinic visit · Today', 'payment-detail', status('₹600 · Paid', 'teal'))}${listRow(icons.pill, 'Bravecto Chewable', 'Pet care · 24 May', 'payment-detail', status('₹1,650 · Paid', 'teal'))}${listRow(icons.file, 'Annual health certificate', '2 May', 'payment-detail', status('₹700 · Pending', 'amber'))}</div>`; }
function renderWallet() { return shell(`${header('Payments & wallet', { brand: true })}<div class="card purple"><p class="tiny" style="opacity:.8">Wallet balance</p><div class="price" style="font-size:38px">₹1,250</div><p class="tiny" style="opacity:.8">Available Respaw credits</p></div>${section('Recent transactions', transactionRows(), `<button class="link-btn" data-route="payment-history">View all ›</button>`)}`, { tab: 'profile' }); }
function renderPaymentHistory() { return shell(`${header('Payment history', { brand: true })}<div class="segment"><button class="active">All</button><button>Payments</button><button>Refunds</button></div>${section('Today', transactionRows())}${section('April 2026', `<div class="card">${listRow(icons.calendar, 'Vaccination', '18 Apr', 'payment-detail', status('₹950 · Refunded', 'teal'))}</div>`)}`, { noNav: true }); }
function renderPaymentDetail() { return shell(`${header('Payment detail', { brand: true })}<div class="card teal"><div class="row between"><div><span class="badge teal">Paid</span><h2 style="margin-top:7px">Dr. Ananya Rao</h2><p class="muted tiny">Video consultation</p></div><div class="price">₹600</div></div></div>${section('Receipt', `<div class="card meta-list"><div class="meta-row"><span>Date & time</span><strong>24 May · 4:30 PM</strong></div><div class="meta-row"><span>Payment method</span><strong>UPI ···· 1234</strong></div><div class="meta-row"><span>Transaction ID</span><strong>TXN1234567890</strong></div><div class="meta-row"><span>Reference</span><strong>RESPAW-2407</strong></div></div>`)}${section('Refund eligibility', `<div class="timeline"><div class="timeline-item done"><span class="timeline-dot"></span><strong>Payment successful</strong><p class="muted tiny">24 May · 4:30 PM</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Refund if requested within policy</strong><p class="muted tiny">Returns to the original method.</p></div></div>`)}${sticky(`<div class="grid-2">${button('View appointment', 'appointment', 'secondary block')}${button('Download receipt', '', 'primary block', 'data-toast="Receipt downloaded"')}</div>`)}`, { noNav: true }); }
function renderPlans() { return shell(`${header('Subscription plans', { brand: true })}<p class="subtitle">Choose the plan that’s right for you and your pets.</p><article class="card" style="margin-top:20px"><div class="row between"><div><span class="badge">Current plan</span><h2 style="margin-top:6px">Free</h2></div><div><strong>₹0</strong><span class="muted tiny"> / month</span></div></div><div class="divider"></div><p class="small">✓ 1 pet &nbsp; ✓ Basic appointments &nbsp; ✓ Reminders</p></article>${['Plus', 'Family'].map((p, i) => `<article class="card ${state.selectedPlan === p ? 'soft' : ''}" style="margin-top:14px;${state.selectedPlan === p ? 'border-color:var(--purple)' : ''}"><div class="row between"><div>${i === 0 ? '<span class="badge">Recommended</span>' : ''}<h2 style="margin-top:5px">${p}</h2><p class="muted tiny">${i === 0 ? 'For pet parents who want more' : 'For multi-pet families'}</p></div><div><strong>₹${i === 0 ? '399' : '699'}</strong><span class="muted tiny"> / month</span></div></div><div class="divider"></div><div class="stack small"><p>✓ Up to ${i === 0 ? '2' : '5'} pets</p><p>✓ Priority appointments</p><p>✓ Unlimited reminders and records</p><p>✓ 24×7 chat support</p></div><button class="${state.selectedPlan === p ? 'primary' : 'secondary'} block" data-plan="${p}" style="margin-top:16px">Choose ${p}</button></article>`).join('')}${section('Frequently asked questions', `<div class="card">${listRow('?', 'Can I change my plan later?', 'Yes, you can change at renewal.', '')}${listRow('?', 'How does billing work?', 'Monthly recurring payment.', '')}</div>`)}`, { tab: 'profile' }); }

function renderArticles() { return shell(`${header('Pet care tips', { brand: true })}<div class="searchbar">${icons.search}<input placeholder="Search trusted pet-care articles"></div><div class="chips" style="margin-top:12px"><button class="chip selected">All</button><button class="chip">Nutrition</button><button class="chip">Wellness</button><button class="chip">Training</button></div><article class="card soft" data-route="article" style="margin-top:22px;cursor:pointer"><div class="media wide"><img src="${IMG.article}" alt="Golden retriever care"></div><span class="badge" style="margin-top:14px">Wellness</span><h2 style="margin-top:7px">A practical guide to healthy ears</h2><p class="muted small">Reviewed by Dr. Meera Iyer · 5 min read</p></article>${section('Latest', `<div class="stack"><article class="card article-card" data-route="article"><div class="media"><img src="${IMG.care}" alt="Dog"></div><div><span class="badge">Nutrition</span><h3 style="margin-top:6px">Choosing the right food for your dog</h3><p class="muted tiny">6 min read</p></div></article><article class="card article-card" data-route="article"><div class="media"><img src="${IMG.luna}" alt="Cat"></div><div><span class="badge">Cat care</span><h3 style="margin-top:6px">Helping indoor cats stay active</h3><p class="muted tiny">4 min read</p></div></article></div>`)}`, { tab: 'home' }); }
function renderArticle() { return shell(`${header('', { brand: true, right: '<button class="icon-btn" data-toast="Share sheet opened">↗</button>' })}<div class="media wide"><img src="${IMG.article}" alt="Healthy dog ears"></div><span class="badge" style="margin-top:18px">Wellness</span><h1 class="title" style="margin-top:8px">A practical guide to healthy ears</h1><p class="muted small" style="margin-top:7px">Reviewed by Dr. Meera Iyer · Updated 20 May 2026 · 5 min read</p><article style="margin-top:24px;font-size:15px;line-height:1.75"><p>Regular ear checks help you notice irritation before it becomes uncomfortable. Healthy ears should look clean and have little or no odor.</p><h2 style="margin:24px 0 8px">What to look for</h2><p>Watch for redness, swelling, discharge, persistent scratching, head shaking, or sensitivity when touched.</p><div class="card amber" style="margin-top:18px"><strong>Talk to a vet</strong><p class="small" style="margin-top:5px">Contact a veterinarian if symptoms worsen, your pet seems in pain, or there is a strong odor or discharge.</p></div><h2 style="margin:24px 0 8px">Gentle routine care</h2><p>Use only products recommended for pets and never insert cotton swabs deeply into the ear canal.</p></article>${sticky(button('Find a vet', 'find-care', 'primary block'))}`, { noNav: true }); }

const settingsGroups = [['Care & pets', [['My pets', 'Pets and health profiles', 'pets', icons.pet], ['Care history', 'Records and prescriptions', 'pet-health', icons.file]]], ['Payments & plan', [['Payments', 'Transactions and refunds', 'wallet', icons.card], ['Subscription plan', 'Free plan', 'plans', icons.card]]], ['Notifications', [['Notification preferences', 'Appointments, care and offers', 'notification-settings', icons.bell]]], ['Security', [['Change password', 'Keep your account secure', 'security', icons.lock]]], ['Help', [['Help center', 'Answers and support', 'help', '?'], ['Contact support', 'We’re here to help', 'help', '◖']]], ['Legal', [['Terms and privacy', 'Policies and medical disclaimer', 'legal', icons.file]]]];
function renderProfile() { return shell(`${header('', { brand: true, bell: true })}<button class="card row" data-route="profile-edit" style="width:100%;text-align:left">${avatar(IMG.priya, 'Priya')}<div class="grow"><h3>Priya Sharma</h3><p class="muted tiny">petpriya@gmail.com<br>+91 98765 43210</p></div><span class="chev">›</span></button>${settingsGroups.map(([g, rows]) => section(g, `<div class="card">${rows.map(([t, n, r, i]) => listRow(i, t, n, r)).join('')}</div>`)).join('')}<div class="stack" style="margin-top:26px">${button('Sign out', 'welcome', 'secondary block')}${button('Delete account', 'delete-account', 'secondary red block')}</div>`, { tab: 'profile' }); }
function renderProfileEdit() { return shell(`${header('Edit profile', { brand: true })}<div style="display:grid;place-items:center;margin-bottom:20px">${avatar(IMG.priya, 'Priya', 'lg')}<button class="link-btn" data-toast="Photo picker opened">Change photo</button></div><form class="form"><div class="field"><label>Full name</label><input class="input" value="Priya Sharma"></div><div class="field"><label>Email</label><input class="input" value="petpriya@gmail.com" readonly><span class="field-help">Verified</span></div><div class="field"><label>Phone</label><input class="input" value="+91 98765 43210"></div><div class="field"><label>City</label><input class="input" value="Bengaluru"></div><div class="field"><label>Address</label><textarea>Koramangala, Bengaluru, Karnataka</textarea></div><button class="secondary block" type="button" data-toast="Current location added">${icons.location} Use my current location</button></form>${sticky(button('Save changes', 'profile', 'primary block', 'data-toast="Profile updated"'))}`, { noNav: true }); }
function renderSecurity() { return shell(`${header('Password & security', { brand: true })}<form class="form"><div class="field"><label>Current password</label><input class="input" type="password" value="respaw123"></div><div class="field"><label>New password</label><input class="input" type="password" placeholder="At least 8 characters"><span class="field-help">Use a number and a mix of upper/lowercase letters.</span></div><div class="field"><label>Confirm new password</label><input class="input" type="password"></div></form>${section('Account security', `<div class="card">${listRow(icons.lock, 'Two-factor authentication', 'Recommended for extra security', '', status('On', 'teal'))}${listRow(icons.user, 'Active sessions', '2 devices signed in', '')}</div>`)}${sticky(button('Update password', 'profile', 'primary block', 'data-toast="Password updated"'))}`, { noNav: true }); }
function renderNotifSettings() { return shell(`${header('Notification preferences', { brand: true })}<p class="subtitle">Choose the updates that are useful to you.</p>${[['Appointments', 'Confirmations, changes and reminders', true], ['Medications & care', 'Dose and vaccination reminders', true], ['Payments', 'Receipts and refund updates', true], ['Pet care tips', 'Helpful educational content', false], ['Offers', 'Respaw plan and clinic offers', false]].map(([t, n, on]) => `<div class="meta-row" style="margin-top:8px"><div><strong>${t}</strong><p class="muted tiny">${n}</p></div><button class="chip ${on ? 'selected' : ''}" data-toggle>${on ? 'On' : 'Off'}</button></div>`).join('')}<div class="callout" style="margin-top:22px">${icons.bell}<p class="muted tiny">Device notifications are currently allowed. Some preferences are prototype-only until backend support is confirmed.</p></div>${sticky(button('Save preferences', 'profile', 'primary block', 'data-toast="Preferences saved"'))}`, { noNav: true }); }
function renderHelp() { return shell(`${header('Help & support', { brand: true })}<div class="searchbar">${icons.search}<input placeholder="Search help topics"></div>${section('Common questions', `<div class="card">${listRow('?', 'How do I reschedule?', 'Open an upcoming appointment.', 'reschedule')}${listRow('?', 'When will my refund arrive?', 'Usually 5–7 business days.', 'payment-detail')}${listRow('?', 'How do online consultations work?', 'Check your camera and microphone.', 'device-check')}</div>`)}${section('Contact us', `<div class="grid-2">${button('Chat with us', '', 'secondary block', 'data-toast="Support chat opened"')}${button('Email support', '', 'primary block', 'data-toast="Email composer opened"')}</div>`)}<div class="card soft" style="margin-top:20px"><strong>Need urgent veterinary care?</strong><p class="muted tiny" style="margin-top:5px">Support cannot provide emergency medical help.</p><button class="link-btn sos" data-route="emergency">Open emergency care</button></div>`, { noNav: true }); }
function renderLegal() { return shell(`${header('Legal & about', { brand: true })}<div class="tabs"><button class="active">Privacy</button><button>Terms</button><button>Refunds</button><button>Medical</button></div><article style="margin-top:22px;line-height:1.7"><h1 class="title">Privacy policy</h1><p class="muted small">Effective 20 July 2026</p><h2 style="margin:24px 0 7px">Your information</h2><p>Respaw uses account, pet, appointment, location, and payment-status information to provide the services you request.</p><h2 style="margin:24px 0 7px">Medical information</h2><p>Pet health records are treated as sensitive product data and are shown only to authorized users and care providers.</p><h2 style="margin:24px 0 7px">Your choices</h2><p>You can update your profile, notification preferences, and account settings from the app.</p></article>`, { noNav: true }); }
function renderDelete() { return shell(`${header('Delete account', { brand: true })}<div class="card danger"><h2>This cannot be undone</h2><p class="muted small" style="margin-top:7px">Deleting your account may affect pet profiles, records, appointments, payments, and active subscriptions.</p></div><div class="stack small" style="margin-top:22px"><p>• Download any records you need first.</p><p>• Cancel upcoming appointments.</p><p>• Review active subscriptions.</p></div><div class="field" style="margin-top:24px"><label>Type DELETE to confirm</label><input class="input" id="deleteConfirm" placeholder="DELETE"></div>${sticky(`<div class="stack">${button('Keep my account', 'profile', 'primary block')}${button('Delete account', '', 'danger-btn block', 'data-action="delete-account"')}</div>`)}`, { noNav: true }); }
function renderServer() { return shell(`${header('Server settings', { brand: true })}<div class="card amber"><strong>Internal development tool</strong><p class="muted tiny" style="margin-top:5px">This page must not appear in production navigation.</p></div><div class="form" style="margin-top:20px"><div class="field"><label>Backend base URL</label><input class="input" value="https://api.respaw.in/api/v1"></div><div class="callout"><div><strong>Build default</strong><p class="muted tiny">https://api.respaw.in/api/v1</p></div></div><div class="grid-2">${button('Test connection', '', 'secondary block', 'data-toast="Connection successful"')}${button('Save override', '', 'primary block', 'data-toast="Server override saved"')}</div><button class="ghost block" data-toast="Reset to build default">Reset to default</button></div>`, { noNav: true }); }

function renderEmergency() { return shell(`${header('Emergency care', { brand: true })}<p class="sos strong">For life-threatening situations only</p><div class="card danger" style="margin-top:16px"><strong>If your pet is experiencing a medical emergency, act fast and contact the nearest clinic.</strong></div>${section('Select pet', `<button class="option-card selected">${avatar(IMG.bruno, 'Bruno')}<span class="grow"><strong>Bruno</strong><span class="muted tiny" style="display:block">Golden Retriever · 3 years</span></span><span class="radio"></span></button>`)}${section('Your location', `<button class="card row" style="width:100%;text-align:left">${icons.location}<span class="grow"><strong>Koramangala, Bengaluru</strong><span class="muted tiny" style="display:block;color:var(--teal)">● Location detected</span></span><span class="chev">›</span></button>`)}<div class="field" style="margin-top:22px"><label>Add notes (optional)</label><textarea placeholder="Describe your pet’s condition briefly…"></textarea></div>${section('What happens next?', `<div class="card small"><p>• We alert the nearest available clinic.</p><p style="margin-top:8px">• A vet or clinic will call you immediately.</p><p style="margin-top:8px">• You receive live guidance and next steps.</p></div>`)}${sticky(`<div class="stack">${button('Call emergency clinic', '', 'secondary red block', 'data-toast="Calling emergency clinic"')}${button('Send SOS alert', '', 'danger-btn block', 'data-action="send-sos"')}</div>`)}`, { noNav: true }); }
function renderSos() { const steps = [['Alert sent', 'Nearest clinics notified'], ['Clinic assigned', 'Paws & Claws Emergency'], ['Vet en route', 'Estimated arrival 8 min'], ['Care started', 'Live assistance in progress']]; return shell(`${header('SOS live tracker', { brand: true, right: status('Live', 'red') })}<div class="map" style="min-height:340px;border-radius:22px"><span class="pin" style="left:28%;top:54%;background:var(--red)"><span>●</span></span><span class="pin" style="left:68%;top:30%"><span>●</span></span></div><div class="card danger" style="margin-top:14px"><div class="row between"><div><span class="badge red">Vet en route</span><h2 style="margin-top:6px">Arriving in 8 min</h2><p class="muted tiny">Dr. Arjun Nair · Paws & Claws Emergency</p></div><strong class="price">8:12</strong></div></div>${section('Live updates', `<div class="timeline">${steps.map((s, i) => `<div class="timeline-item ${i < state.sosStage ? 'done' : i === state.sosStage ? 'active' : ''}"><span class="timeline-dot"></span><strong>${s[0]}</strong><p class="muted tiny">${s[1]}</p></div>`).join('')}</div>`)}${sticky(`<div class="grid-2">${button('Call clinic', '', 'secondary red block', 'data-toast="Calling clinic"')}${button('Advance demo', '', 'primary block', 'data-action="advance-sos"')}</div>`)}`, { noNav: true }); }

function genericRoute(route) {
  const p = pages.find(x => x[1] === route); return shell(`${header(p?.[2] || 'Respaw', { brand: true })}<div class="empty"><div class="empty-mark">${icons.pet}</div><h2>${p?.[2] || 'Page'}</h2><p class="muted small" style="margin-top:7px">This product surface uses the shared Respaw design system and connected prototype navigation.</p>${button('Back to Home', 'home', 'primary', 'style="margin-top:18px"')}</div>`, { noNav: true });
}

const renderers = {
  splash: renderSplash, welcome: renderWelcome, 'sign-in': renderSignIn, otp: renderOtp, 'create-account': renderAccount, 'reset-password': renderReset,
  home: renderHome, notifications: renderNotifications, 'find-care': renderFindCare, 'search-filters': renderFilters, map: renderMap, vet: renderVet, reviews: renderReviews,
  'booking-pet': renderBookingPet, 'booking-time': renderBookingTime, 'booking-reason': renderBookingReason, 'booking-review': renderBookingReview, payment: renderPayment, confirmation: renderConfirmation,
  appointments: renderAppointments, appointment: renderAppointment, reschedule: renderReschedule, cancel: renderCancel, review: renderReview,
  modality: renderModality, 'device-check': renderDeviceCheck, consultation: renderConsultation, 'consultation-chat': renderConsultChat, 'visit-summary': renderVisitSummary, assistant: renderAssistant,
  pets: renderPets, 'pet-edit': renderPetEdit, 'pet-health': renderPetHealth, timeline: renderTimeline, 'medical-record': renderMedicalRecord, medications: renderMedications, 'medication-edit': renderMedicationEdit, reminders: renderReminders, 'reminder-edit': renderReminderEdit, prescriptions: renderPrescriptions, documents: renderDocuments,
  wallet: renderWallet, 'payment-history': renderPaymentHistory, 'payment-detail': renderPaymentDetail, plans: renderPlans, articles: renderArticles, article: renderArticle,
  profile: renderProfile, 'profile-edit': renderProfileEdit, security: renderSecurity, 'notification-settings': renderNotifSettings, help: renderHelp, legal: renderLegal, 'delete-account': renderDelete, 'server-settings': renderServer,
  emergency: renderEmergency, 'sos-tracker': renderSos
};

const screenEl = document.getElementById('screen');
const pageIndex = document.getElementById('pageIndex');
const searchInput = document.getElementById('pageSearch');
const toastEl = document.getElementById('toast');
const modalRoot = document.getElementById('modalRoot');
let toastTimer;

function currentRoute() { return location.hash.replace(/^#\/?/, '') || 'splash'; }
function navigate(route) { location.hash = `#/${route}`; }
function showToast(message) { toastEl.textContent = message; toastEl.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toastEl.classList.remove('show'), 2200); }
function renderIndex(filter = '') {
  let group = ''; pageIndex.innerHTML = pages.filter(p => p[2].toLowerCase().includes(filter.toLowerCase()) || p[0].toLowerCase().includes(filter.toLowerCase())).map((p, i) => { const h = p[0] !== group ? `<div class="index-group">${group = p[0]}</div>` : ''; return `${h}<button class="index-link ${currentRoute() === p[1] ? 'active' : ''}" data-route="${p[1]}"><span class="index-no">${String(pages.indexOf(p) + 1).padStart(2, '0')}</span>${p[2]}</button>`; }).join('');
}
function render() { const route = currentRoute(); modalRoot.innerHTML = ''; screenEl.innerHTML = (renderers[route] || (() => genericRoute(route)))(); renderIndex(searchInput.value); screenEl.scrollTop = 0; screenEl.focus({ preventScroll: true }); }

function openModal(title, body, actions = '') {
  modalRoot.innerHTML = `<div class="modal-backdrop" data-close-modal><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="modal-handle"></div><h2 id="modalTitle">${title}</h2><div style="margin-top:14px">${body}</div>${actions ? `<div class="stack" style="margin-top:20px">${actions}</div>` : ''}</section></div>`;
}
function closeModal() { modalRoot.innerHTML = ''; }

document.addEventListener('click', (event) => {
  const route = event.target.closest('[data-route]')?.dataset.route; if (route) { navigate(route); return; }
  if (event.target.closest('[data-back]')) { history.length > 1 ? history.back() : navigate('home'); return; }
  const toast = event.target.closest('[data-toast]')?.dataset.toast; if (toast) { showToast(toast); }
  if (event.target.matches('[data-close-modal]')) closeModal();
  const action = event.target.closest('[data-action]')?.dataset.action;
  if (action === 'care') { state.careGiven = !state.careGiven; showToast(state.careGiven ? 'Bravecto marked as given' : 'Care task restored'); render(); }
  if (action === 'read-all') { state.notificationsRead = true; showToast('All notifications marked read'); render(); }
  if (action === 'pay') { openModal('Confirming payment', `<div class="empty" style="padding:20px"><div class="success-mark">${icons.check}</div><h3>Payment verified</h3><p class="muted small">₹600 was paid securely.</p></div>`, button('View confirmation', 'confirmation', 'primary block')); }
  if (action === 'send-sos') { openModal('Send SOS alert?', `<div class="card danger"><strong>Nearest clinics will be alerted</strong><p class="muted small" style="margin-top:5px">Your selected pet, location, and notes will be shared.</p></div>`, `${button('Send SOS now', 'sos-tracker', 'danger-btn block')}${button('Go back', '', 'ghost block', 'data-action="close-modal"')}`); }
  if (action === 'advance-sos') { state.sosStage = Math.min(3, state.sosStage + 1); showToast('SOS status advanced for demo'); render(); }
  if (action === 'end-call') { openModal('End consultation?', `<p class="muted small">You can rejoin from the appointment if the session remains active.</p>`, `${button('End consultation', 'visit-summary', 'danger-btn block')}${button('Stay in call', '', 'secondary block', 'data-action="close-modal"')}`); }
  if (action === 'close-modal') closeModal();
  if (action === 'reset-link') { showToast('Reset instructions sent'); }
  if (action === 'submit-account') { navigate('home'); showToast('Welcome to Respaw'); }
  if (action === 'delete-account') { const v = document.getElementById('deleteConfirm')?.value; if (v === 'DELETE') { navigate('welcome'); showToast('Prototype account deleted'); } else showToast('Type DELETE to confirm'); }
  if (action === 'add-menu') { openModal('Add to Bruno’s health', `<div class="card">${listRow(icons.file, 'Medical record', 'Visit, vaccination or note', 'medical-record')}${listRow(icons.pill, 'Medication', 'Dose and schedule', 'medication-edit')}${listRow(icons.calendar, 'Reminder', 'Care task or appointment', 'reminder-edit')}${listRow(icons.file, 'Document', 'Report, scan or certificate', 'documents')}</div>`); }
  if (action === 'send-assistant') { const input = document.getElementById('assistantInput'); if (input?.value.trim()) { state.messages.push({ from: 'me', text: input.value.trim() }, { from: 'bot', text: 'Thanks for sharing that. I can offer general guidance or help you find a veterinarian.' }); render(); } }
  if (action === 'send-consult') { const input = document.getElementById('consultInput'); if (input?.value.trim()) { showToast('Message sent to Dr. Ananya'); input.value = ''; } }
  const pet = event.target.closest('[data-select-pet]'); if (pet) { state.booking.pet = pet.dataset.selectPet; render(); }
  const type = event.target.closest('[data-select-type]'); if (type) { state.booking.type = type.dataset.selectType; render(); }
  const slot = event.target.closest('[data-slot]'); if (slot) { state.booking.time = slot.dataset.slot; render(); }
  const date = event.target.closest('[data-date]'); if (date) { state.booking.date = date.dataset.date + ', May'; render(); }
  const apptTab = event.target.closest('[data-appt-tab]'); if (apptTab) { state.appointmentTab = apptTab.dataset.apptTab; render(); }
  const plan = event.target.closest('[data-plan]'); if (plan) { state.selectedPlan = plan.dataset.plan; showToast(`${state.selectedPlan} selected`); render(); }
  const toggle = event.target.closest('[data-toggle]'); if (toggle) { toggle.classList.toggle('selected'); toggle.textContent = toggle.classList.contains('selected') ? 'On' : 'Off'; }
  const call = event.target.closest('[data-call]'); if (call) { state.call[call.dataset.call] = !state.call[call.dataset.call]; call.style.opacity = state.call[call.dataset.call] ? '1' : '.45'; showToast(`${call.dataset.call} ${state.call[call.dataset.call] ? 'on' : 'off'}`); }
  const prompt = event.target.closest('[data-prompt]'); if (prompt) { state.messages.push({ from: 'me', text: prompt.dataset.prompt }, { from: 'bot', text: 'I can help with general guidance. Tell me what you have noticed and for how long.' }); render(); }
  const filter = event.target.closest('[data-filter]'); if (filter) { state.searchFilter = filter.dataset.filter; document.querySelectorAll('[data-filter]').forEach(x => x.classList.toggle('selected', x === filter)); showToast(`${state.searchFilter} filter applied`); }
  const modality = event.target.closest('[data-modality]'); if (modality) { document.querySelectorAll('[data-modality]').forEach(x => x.classList.toggle('selected', x === modality)); showToast(`${modality.dataset.modality} consultation selected`); }
});

document.addEventListener('submit', (event) => { event.preventDefault(); if (event.target.dataset.form === 'signin') { navigate('home'); showToast('Signed in successfully'); } });
window.addEventListener('hashchange', render);
searchInput.addEventListener('input', () => renderIndex(searchInput.value));
render();
